Rev swerve
Team2537/2024Crescendo pull request #85
Opened 2024-10-01 18:19 UTC by falOn-Dev

2024-10-01 19:10 UTC, Something-Inconspicuous requested changes
I am not entirely sure when we should use `Measure<Angle>` vs `Rotation2d`.

The arrays of data in the swerve implementation seem to be able to be consolidated, so I would like that to happen.

2024-10-01 19:10 UTC, Something-Inconspicuous commented on src/main/java/frc/robot/subsystems/swerve/Drivebase.kt
> +    fun setVisionSTDDevs(xMeters: Double, yMeters: Double, rotRads: Double) {
Measures should be used here

2024-10-01 19:10 UTC, Something-Inconspicuous commented on src/main/java/frc/robot/subsystems/swerve/Drivebase.kt
> +        )
I'm not entirely sure, but these being differentiated by direction while in the rest of the subsystem being referenced by index doesn't sit right with me.

I would prefer if we just had a small inner class to wrap everything those arrays hold with named parts.

2024-10-01 19:10 UTC, Something-Inconspicuous commented on src/main/java/frc/robot/subsystems/swerve/gyro/GyroIO.kt
> +        var rollVelocityDegreesPerSecond: Double = 0.0
Using Rotation2d is interesting; is it preferable to measures? Regardless, the velocities should definitely be measures

2024-10-01 19:10 UTC, Something-Inconspicuous commented on src/main/java/frc/robot/subsystems/swerve/gyro/GyroIO.kt
> +    }
Use a non-null table parameter.

2024-10-01 19:10 UTC, Something-Inconspicuous commented on src/main/java/frc/robot/subsystems/swerve/gyro/GyroIO.kt
> +    fun setYaw(newYaw: Double) {}
Measure

2024-10-01 19:10 UTC, Something-Inconspicuous commented on src/main/java/frc/robot/subsystems/swerve/module/ModuleIO.kt
> +        var turnSupplyCurrent: Double = 0.0
I would have done a nested class, but I'm not gonna cry over it

2024-10-01 19:10 UTC, Something-Inconspicuous commented on src/main/java/frc/robot/subsystems/swerve/Drivebase.kt
> +    private val modules: Array<SwerveModule> = arrayOf(
I am extremely curious as to why this is an array.

2024-10-01 19:10 UTC, Something-Inconspicuous commented on src/main/java/frc/robot/subsystems/swerve/Drivebase.kt
> +    private val modulePositions: Array<SwerveModulePosition> = Array(4) { SwerveModulePosition() }
I think these three arrays can (and should) be consolidated into one array of a wrapper class for these modules, like a `SwerveModuleData` or something

2024-10-04 14:27 UTC, mteam88 approved these changes

2024-10-04 14:35 UTC, merged